name: Syncer

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Sync with upstream
      run: |
        git config --global user.name "zclkkk"
        git config --global user.email "zclkkk@outlook.com"

        git clone https://github.com/MikaWrt/openwrt -b master && cd openwrt
        git fetch https://github.com/openwrt/openwrt master
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/openwrt master
        cd ..
        rm -rf openwrt
        git clone https://github.com/MikaWrt/openwrt -b openwrt-21.02 && cd openwrt
        git fetch https://github.com/openwrt/openwrt openwrt-21.02
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/openwrt openwrt-21.02
        cd ..
        rm -rf openwrt

        git clone https://github.com/MikaWrt/packages -b master && cd packages
        git fetch https://github.com/openwrt/packages master
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/packages master
        cd ..
        rm -rf packages
        git clone https://github.com/MikaWrt/packages -b openwrt-21.02 && cd packages
        git fetch https://github.com/openwrt/packages openwrt-21.02
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/packages openwrt-21.02
        cd ..
        rm -rf packages

        git clone https://github.com/MikaWrt/luci -b master && cd luci
        git fetch https://github.com/openwrt/luci master
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/luci master
        cd ..
        rm -rf luci
        git clone https://github.com/MikaWrt/luci -b openwrt-21.02 && cd luci
        git fetch https://github.com/openwrt/luci openwrt-21.02
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/luci openwrt-21.02
        cd ..
        rm -rf luci

        git clone https://github.com/MikaWrt/routing -b master && cd routing
        git fetch https://github.com/openwrt/routing master
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/routing master
        cd ..
        rm -rf routing
        git clone https://github.com/MikaWrt/routing -b openwrt-21.02 && cd routing
        git fetch https://github.com/openwrt/routing openwrt-21.02
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/routing openwrt-21.02
        cd ..
        rm -rf routing

        git clone https://github.com/MikaWrt/telephony -b master && cd telephony
        git fetch https://github.com/openwrt/telephony master
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/telephony master
        cd ..
        rm -rf telephony
        git clone https://github.com/MikaWrt/telephony -b openwrt-21.02 && cd telephony
        git fetch https://github.com/openwrt/telephony openwrt-21.02
        git rebase FETCH_HEAD
        git push -f https://zclkkk:${TOKEN}@github.com/MikaWrt/telephony openwrt-21.02
        cd ..
        rm -rf telephony

      env:
        TOKEN: ${{ secrets.TOKEN }}
